# Generated by Django 4.1.1 on 2022-09-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmail', '0004_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SendEmail.users'),
            preserve_default=False,
        ),
    ]
