# Generated by Django 4.1.1 on 2022-09-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmail', '0005_emaillog_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
