# Generated by Django 4.1.1 on 2022-09-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmail', '0006_delete_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('emailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SendEmail.emaildata')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SendEmail.users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
