# Generated by Django 4.1.1 on 2022-09-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmail', '0007_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='emailid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SendEmail.emaildata'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SendEmail.users'),
        ),
    ]
