# Generated by Django 4.1.1 on 2022-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmail', '0009_receivedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedemail',
            name='name',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
    ]
