# Generated by Django 4.1.1 on 2022-09-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmail', '0010_receivedemail_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivedEMail',
        ),
    ]
